### ISSUE TITLE
Links in email-domain-acceptlist.md do not work

### ISSUE THREAD

**Issue by codeindustriesnl** [keycloakify/docs.keycloakify.dev#10]
Hi,

The links in the page https://docs.keycloakify.dev/email-domain-acceptlist do not work for me (giving a 404). 

Specifically:

- https://github.com/etalab/sill-web/blob/20e1500166708da75fcad4ebfb9f6e1d39b462c0/src/ui/components/KcApp/kcContext.ts#L53
- https://github.com/etalab/sill-web/blob/main/src/bin/emails_domain_accept_list_helper.ts

**Comment by garronej** [comment]
Thank you for reporting.  

I updated the links https://docs.keycloakify.dev/email-domain-acceptlist
